### ISSUE TITLE
Killing processes after test execution [@nx-extend/e2e-runner:run]

### ISSUE THREAD

**Issue by pkonieczniak** [TriPSs/nx-extend#90] opened 2022-12-07 12:25 UTC
Is there any option to enforce terminating processes after tests execution? At this moment frontend-server or backend server is still alive.

I have to use `"reuseExistingServer": true` in each `project.json` configuration, but it doesn't solve the problem when frontends are served under the same port.

```
 yarn test-e2e-frontend-all
```

- The first project will pass the test
- The second one is failing because under port 8080 is served first application
- The third test will fail because under port 8080 is served first application

We could add a new flag for the target: `terminateExistingServer`. In the case where the port is already taken, we could terminate the process and after call `launchProcess` function.

Perfect if it would be possible to kill apps after tests executions or after terminating e2e target.

**Comment by TriPSs** [comment] 2022-12-07 14:34
Servers that the runner started should also be killed after the tests are done.

Adding a option `terminateExistingServer` could also be a good thing, that we use for example `npx kill-port <port>` before running to make sure that the port is free.

**Comment by pkonieczniak** [comment] 2022-12-07 15:07
I looked into the library code, and as you said it looks that processes should be killed after test executions.
I guess that in my case it doesn't work as it should because of nx, node or Cypress version.
-node v14.18.0
-cypress v^9.0.0" (deprecated)
-nx v15.2.4

As a workaround I changed my target to something like that:

```json
    "test-e2e-frontend": {
      "executor": "nx:run-commands",
      "options": {
        "commands": [
          "kill-port 8080,3601 && nx serve ss-front:start-e2e-frontend"
        ],
        "pararell": false
      }
    },
    "start-e2e-frontend": {
      "executor": "@nx-extend/e2e-runner:run",
      // rest of the code
```

It's still not the best solution because after test execution some processes could still work, but as Cypress docs said `Most CI providers will automatically kill background processes so you don't have to worry about cleaning up your server process once Cypress finishes.`

**Comment by simondotm** [comment] 2022-12-15 23:53
I have a target that uses `nx:run-commands` to run a custom serve process, and CTRL+C exit doesn't pass onto the spawned command - ideally this would be possible.
I'm using v15.2.1

**Comment by TriPSs** [comment] 2023-11-09 14:06
Closing this as with the latest version I cannot reproduce this anymore (When running in UI mode and doing CTRL+C).

**Closed by TriPSs** 2023-11-09 14:06 UTC
